### ISSUE TITLE
Sometimes the favicon disappears

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#108]
No idea when or why this happens. Did you also observe this @v1r0x @Henni?

**Comment by v1r0x** [comment]
Same here, but I think this is not a maps-related issue. I think I already had this in the news app.

**Comment by jancborchardt** [comment]
Pretty sure this was fixed by adding the custom favicon, right? https://github.com/owncloud/maps/pull/110

**Comment by v1r0x** [comment]
At least I didn't observe it since then.
