### ISSUE TITLE
Unify popup data display & style

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#109]
There’s a bunch of different ways we currently display info in the popup. And we should make it so it all has a consistent look.

The favorite popup is the best example at the moment. Nice h2 header with the most important thing in it. Not much other info though – partly by design (like not having the coordinates etc) but partly it would be cool to have details like address and opening hours.
![capture du 2015-12-31 11-31-51](https://cloud.githubusercontent.com/assets/925062/12132203/e4579ba0-b419-11e5-9bdf-7f4d35152848.png)

The opposite here in the POI popup, basically a raw database dump. This is the same store as above, but that’s completely lost in the sea of other info.
![capture du 2015-12-31 11-32-32](https://cloud.githubusercontent.com/assets/925062/12132202/e42edda0-b419-11e5-890f-dffd8164bc02.png)
A nice display of this data would be:
> **Suicycle Store**
> Wohlwillstraße 12, 20359 Hamburg (St. Pauli)
> +49…_clickable phone number for mobile use_
> [suicycle-store.com ↗](http://suicycle-store.com/) _clickable link, opens externally_
> [Navigate here] _as a button_

Here for when you click on the map:
![capture du 2015-12-31 11-31-33](https://cloud.githubusercontent.com/assets/925062/12132204/e457e254-b419-11e5-8818-1f1aa98aef1d.png)
Same exercise:
> **Porsche Design**
> Poststraße 2–4, 20354 Hamburg (Neustadt)
> [Navigate here]

Extra boroughs and especially the country can just be left out. We mainly need to cut out useless info and reorder the rest.

And yet another format where the commas were already replaced by line breaks:
![capture du 2015-12-31 11-30-41](https://cloud.githubusercontent.com/assets/925062/12132205/e4594bc6-b419-11e5-8430-78993e73499d.png)
> **Gruner + Jahr**
> Am Baumwall 11, Hamburg (Mitte)
> [Navigate here]

**Comment by v1r0x** [comment]
Absolutely! I don't know how we could unify those informations. I'll look into it soon, hopefully ;)

**Comment by jancborchardt** [comment]
In the first case (2nd screenshot) it’s the `name` property, and in the other two examples it’s the first element. So that could always be the `h2`, and the rest in the following `p`. That would already be a massive improvement.

**Comment by v1r0x** [comment]
I'll have a look at it after the weekend, but we should wait with commits, because I changed some stuff in the other PRs, which would only lead to massive merge conflicts.

**Comment by jancborchardt** [comment]
Yup, sure.

**Comment by v1r0x** [comment]
Here's a list of different types we have:
- [x] POI
- [ ] normal marker v1
- [ ] normal marker v2
- [ ] favorites
