### ISSUE TITLE
Grey bar below search field

### ISSUE THREAD

**Issue by Henni** [owncloud/maps#113]
![image](https://cloud.githubusercontent.com/assets/1267827/12267810/305f770e-b94a-11e5-960b-d3fe96330513.png)

I couldn't find the origin of this bar in the css.
Maybe you find it @jancborchardt @v1r0x

**Comment by v1r0x** [comment]
I think this is part of the routing-machine. This will be replaced in #111, hopefully ;)

**Comment by v1r0x** [comment]
Is this on master?

**Comment by Henni** [comment]
@v1r0x yes it is

**Comment by v1r0x** [comment]
@Henni I'm on master too, but can not reproduce it. In firefox you could use rightclick>Inspect Element to get the corresponding element.

**Comment by v1r0x** [comment]
Ok, I also have it (in Chrome) and as said it is part of the routing-machine, which will be replaced in #111. So I'll close.

**Comment by Henni** [comment]
@v1r0x Great thanks!
