### ISSUE TITLE
»This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later.«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#116]
@v1r0x @Henni @brantje what’s the minimum version we run on? We should put that in the info.xml

**Comment by v1r0x** [comment]
Isn't there a `requiremin` in this file? Or is this something else?
Nevertheless, I think we are 8+ or 8.1+, but not completely sure.

**Comment by jancborchardt** [comment]
See https://github.com/owncloud/core/pull/21808/files#diff-fea49f0732d061e089d5ce81b2483176L10 on how the syntax needs to be :)

**Comment by Henni** [comment]
`requiremin` is currently set to 7.
But we should replace it with `<owncloud min-version="7.0" />` and maybe increase it even to 9.0.

**Comment by v1r0x** [comment]
Any reason for 9.0? The current max shouldn't be higher than 8.2. Otherwise we would bar people from this app.

**Comment by jancborchardt** [comment]
So min 8.2 and max 9.0?

**Comment by Henni** [comment]
@jancborchardt :+1:

**Comment by v1r0x** [comment]
:+1:
