### ISSUE TITLE
Strange search results

### ISSUE THREAD

**Issue by Henni** [owncloud/maps#128]
What are the last four results?
![image](https://cloud.githubusercontent.com/assets/1267827/12948290/61895e44-d001-11e5-92fe-6b1a4eeb79ae.png)

**Comment by v1r0x** [comment]
Entries with a star icon should be favorites.

**Comment by Henni** [comment]
Was irritated by them all having the same name, but looks like I actually created all of these...

**Comment by v1r0x** [comment]
The initial names should be more meaningful since #124 ;)
