### ISSUE TITLE
Make map full-content, overlay search box, show sidebar only when needed

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#2]
Ok @houqp @emerzh let’s do this. If you like we can have a call about this soon. :)

* As a start it should be very simple, full-content map
* no fixed sidebar (unlike News or Notes) – but it can appear contextually, e.g. for routing or list of favorites
* Search field and any elements slightly transparent over the map.
* Places directly marked in the map, e.g. favorites or search results

See the new Google Maps or [GNOME Maps](https://wiki.gnome.org/Design/Apps/Maps) for inspiration.

**Comment by jancborchardt** [comment]
@v1r0x if you find where to set the search box position in leaflet, let me know.

**Comment by v1r0x** [comment]
This is currently done with some magic in `js/script.js` but since we want to replace the search, I don't want to spend too much time to understand this.

**Comment by v1r0x** [comment]
@jancborchardt Could you fix the sidebar that it is hidden by default?

**Comment by jancborchardt** [comment]
Yeah. I’m even thinking of removing the navigation bar completely for now and gradually adding back the things we need. The favorites and contacts layer toggle for example we can just display below or near the search box, right?

**Comment by v1r0x** [comment]
I like how it is done in the google maps app on android. Having a full-screen map and swipe to the right to show the layer overlay.

**Comment by jancborchardt** [comment]
Done at https://github.com/owncloud/maps/pull/101, please review! :)
