### ISSUE TITLE
Show tracks on map

### ISSUE THREAD

**Issue by gpxtrack** [owncloud/maps#30]
Great app :-)  I like the options menu to display additional information on the map. 
I wonder if it's possible to implement functionality for viewing tracks from the uploaded files. I know there is a GPX viewer app but it doesn’t work with OC7 and it seems that the further development is discontinued. Any how it would be great to view a chosen track and toggle nearby contacts shops etc...
Would it be possible to implement this kind of functionality?

**Comment by DJaeger** [comment]
For more information on tracking your device see here:
https://github.com/owncloud/maps/issues/28

**Comment by DJaeger** [comment]
Please close this issue and continue to track this in #39.
That issue includes this one with addition of KML and some more informations.
