### ISSUE TITLE
Todo list summer 2015

### ISSUE THREAD

**Issue by brantje** [owncloud/maps#41]
So in the week of 3-8 till 9-8 i have a week off, and i decided to spend that time on the maps app.
This issue will contain all the little issues i want todo in that week.
If you have any additions, feel free to submit them.
- [ ] Issue #21 
- [ ] Issue #22

**Comment by jancborchardt** [comment]
@brantje any progress here? :) Do you need some help?

**Comment by jancborchardt** [comment]
Btw, it would be cool to focus on the basic milestone: https://github.com/owncloud/maps/milestones/0.1%20%E2%80%93%20the%20basics :)

**Comment by jancborchardt** [comment]
Closing this for now – let's continue in the respective issues. :)
