### ISSUE TITLE
https://www.openstreetmap.org

### ISSUE THREAD

**Issue by hitam4450** [owncloud/maps#45]
Suggestion:

How about to incorporate https://www.openstreetmap.org into OwnCloud ???

Regards, hitam4450

**Comment by DJaeger** [comment]
What kind of incorporation do you mean?

**Comment by hitam4450** [comment]
OKI, I just installed the app and checked it out a little bit. So far, so good! However I use MAPS.ME Version 4.4.7, which uses OpenstreetMap as their base of information. I do have a large number of Bookmarks of locations, which I would like to import into the maps app. The file format for export is named .kmz ! I uploaded the file to a folder in the Fies directory, but I could not find any possibility to import these bookmarks.
Is or will it be possible to import bookmarks files into maps??

regards, hitam4450

**Comment by hitam4450** [comment]
Is it possible to make the left side panel visible / nonvisible with a toggle switch, what i suggested already in other apps, to make a small screen size more efficient ??

regards, hitam

**Comment by Henni** [comment]
@hitam4450 this is what happens on mobile/small screens:
![image](https://cloud.githubusercontent.com/assets/1267827/9170603/8ba7347c-3f64-11e5-9b4d-21adcebd0297.png)

**Comment by hitam4450** [comment]
The reasoning is to maximize of the viewing area........!

**Comment by DJaeger** [comment]
You can toggle the left bar with the icon top left with the three horizontal bars as (nearly) all other ownCloud apps too.

Showing kmz and gpx is already proposed in #39, but no "importing".
What do the others think, should the app also be able to import and save them to db?
It would be similar to what is happening for location tracking.

@hitam4450: Could you please rename the issue to "importing of locations and tracks"?

**Comment by Henni** [comment]
@DJaeger It would be great to store such data in the database and also edit it within the app.
But this is an issue for later.

**Comment by DJaeger** [comment]
At least after #39.

**Comment by hitam4450** [comment]
@DJaeger  Sorry, I do not see any icon top left with three horizontal bars.. OC 8.0.5.2!

**Comment by Henni** [comment]
@hitam4450 it's only displayed on small screens. Try resizing your browser.

**Comment by DJaeger** [comment]
You can see, how it should look like in @Henni's Screenshot.
If it looks other for you please post a screenshot and which browser with which version you are using.

**Comment by hitam4450** [comment]
Well I use FF 39.0.3. I switched from full screen mode to a smaller mode and then I could see the 3 bars... still strange and cumbersome.........!

**Comment by Henni** [comment]
That is the intended behavior. The sidebar should only be hidden if the window is too small and more screen space is needed.

**Comment by hitam4450** [comment]
Ic...thanks for the enlightenment! On my 10" netbook screen  the sidebar takes a large portion of the screen!

**Comment by hitam4450** [comment]
Just uninstalled the app!

**Comment by DJaeger** [comment]
@hitam4450: You are still unclear!
What is strange and cumbersome?
Please be more clear so we can help you!

**Comment by brantje** [comment]
@hitam4450 means that the sidebar doesn't collapse on mobile.

**Comment by hitam4450** [comment]
especially on smaller screens, e.g. 10" netbook screen....... or tablets........

**Comment by hitam4450** [comment]
sorry, for my confusing comments........

**Comment by DJaeger** [comment]
@brantje: If that is what @hitam4450 means that would be a bug and this should not be closed.
But as he speaks of a 10" display, this is a display of "middle big" size.
I'm not sure where the breakpoints are, but I think they are not recognized as "small" display.
So his behaviour would be correct.

**Comment by Henni** [comment]
The breakpoint is at about 768 pixels I think.

**Comment by stefan-niedermann** [comment]
cc @owncloud/designers 
cc @jancborchardt 

summary: There is a user with a 10" notebook. in his opinion the sidebar should be collapsible at this size because it takes too much space.
this is not only a maps issue. maybe a reconsideration-issue should be opened in core?

**Comment by DJaeger** [comment]
@Henni: Yes, you are correct. 768px is the max for the toggle.

**Comment by jancborchardt** [comment]
Yes, I think in the case of Maps (and also probably Calendar) the default should be to hide the sidebar (mobile mode).

Then though we still have to display the search box. Otherwise it will be a 2-step process to search.

**Comment by jancborchardt** [comment]
Also @hitam4450 maybe take a bit more time to think your comments through, and use less exclamation marks (!). It comes off as rude and unhelpful otherwise. Thanks!

**Comment by DJaeger** [comment]
The searchbox could be displayed, as on osm.org when expended the menu, inside a bar on the top.
Or like GMaps as flying layer.

**Comment by hitam4450** [comment]
I  certainly agree to the discussion if the left side panel should be collapsible in Core - as a general feature - or by individually each app! Opened the discussion prior in other apps!

regards., hitam4450

**Comment by jancborchardt** [comment]
@DJaeger yeah, like Gmaps is what I’m thinking. An always visible part of the left sidebar. And the sidebar only expands when you press the menu button.

**Comment by Henni** [comment]
@jancborchardt can we solve this in core maybe by implementing a javascript function which enables the switch? Or should the maps app simply override the css rule?

**Comment by jancborchardt** [comment]
@Henni maybe it needs some adjustment from core, yes. Not sure about that though – do you want to look into that?

Essentially then the Maps app should be able to say something like »mobile mode by default« so the sidebar is hidden and only the switch is visible, even for desktops.

**Comment by Henni** [comment]
@jancborchardt that's what I had in mind.
I won't look into this now. Maybe in a few days.
Could you create an issue for this? And if you like you can assign me ;)

**Comment by DJaeger** [comment]
Please use this issue for maintaining the change in this app as this is the purpose of this issue.
It simply needs to be renamed to be more clear.

**Comment by jancborchardt** [comment]
Nah, this issue started out as something completely different. I opened a new one in core: https://github.com/owncloud/core/issues/18213
