### ISSUE TITLE
Type icons not found

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#46]
Currently Maps gives some errors about not found type icons:
```
[…]
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: gallery
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: motel
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: museum
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: theme_park
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: zoo
```

@Brantje @DJaeger

**Comment by DJaeger** [comment]
For theme_park we currently do not have an icon available.
All others are fixed in #36.

**Comment by DJaeger** [comment]
Have also added theme_park

**Comment by DJaeger** [comment]
@brantje: are you still maintaining this repo?
If not or if you don't have the time to take care of it, would you give someone the permissions to do so, that this app can move forward?

**Comment by jancborchardt** [comment]
@Djaeger if you want to step up and join the Maps team that would be awesome! :) I'll be there to help regarding design.

@karlitschek can you add @DJaeger to the ownCloud organization?

**Comment by DJaeger** [comment]
I'd be glad to.

**Comment by jancborchardt** [comment]
Reopening cause of the JS errors it spams in the log. @DJaeger would be cool if you find the time to add the rest. :)

**Comment by v1r0x** [comment]
Can we close this? Shouldn't happen with new #112

**Comment by v1r0x** [comment]
Should be fixed, please reopen if still persists
