### ISSUE TITLE
Integrate maki icons

### ISSUE THREAD

**Issue by Henni** [owncloud/maps#52]
Integrate the maki icons which are already used in this repository.
This reduces requests to external sites and would reduce the list of Content-Security-Policies.

**Comment by DJaeger** [comment]
They can be found here:
https://github.com/mapbox/maki

This would also allow owncloud to hande the caching itself.

**Comment by jancborchardt** [comment]
@Henni do you mean as replacement for these markers here?
![capture du 2015-12-30 16-05-23](https://cloud.githubusercontent.com/assets/925062/12052423/372d51b8-af0f-11e5-923f-df1c3d157d4d.png)

**Comment by v1r0x** [comment]
fixed in #112? @Henni

**Comment by Henni** [comment]
:+1:
