### ISSUE TITLE
Deactivate »Contacts« entry if contacts app is not installed or there are no contacts

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#59]
From https://github.com/owncloud/maps/pull/58#issuecomment-130064294:

> If the Contacts app is not installed, simply do not show the entry in the sidebar and deactivate the functionality.

**Comment by jancborchardt** [comment]
cc @v1r0x @Henni

**Comment by v1r0x** [comment]
hope #60 works :)
the PR is based on master, not on #58 so one has to merge these two

**Comment by v1r0x** [comment]
I didn't saw the "or there are no contacts". But I would still display it if the user has no contacts. Otherwise the user wouldn't know that there is this cool feature ;)

**Comment by jancborchardt** [comment]
Fixed by @v1r0x with https://github.com/owncloud/maps/pull/60

Thanks a bunch! :)
