### ISSUE TITLE
Import (syncing) of KMZ files 

### ISSUE THREAD

**Issue by hitam4450** [owncloud/maps#70]
Hi,

I use an ANDROID off line map  (MAPS.ME), which stores my locations of interests in KMZ based files.

1. Would it be possible to import KMZ files, exported from the app,  into maps to be displayed?

2. Of course syncing these files would be even more advantageous, however it is much more work and larger effort to implement this feature!

regards, hitam4450

**Comment by v1r0x** [comment]
The first part is covered in #39 
For the second one: I don't know how and where MAPS.ME stores the kmz files.

**Comment by hitam4450** [comment]
Hi,

MAPS.ME stores the kmz files in its bookmark meu item. By sharing them e.g. with Owncloud, I will be able to upload it to OC. How importing them and make them display in maps??

**Comment by v1r0x** [comment]
as said, the possibility to load and display kml files is covered in #39 
In the current version only gpx files are supported, but it will work the same way for kml files.
