### ISSUE TITLE
Icon of maps

### ISSUE THREAD

**Issue by hitam4450** [owncloud/maps#74]
The icon of maps is almost identical with the icon of pinnit!
![pinit](https://cloud.githubusercontent.com/assets/9738727/9699747/bd9e38a2-53ed-11e5-9b50-27e7dec55ce9.png)

regards, hitam4450

**Comment by v1r0x** [comment]
that's true.
Maybe we could change it to something similar to google maps? @jancborchardt 
or @libasys has an idea for pinit?

cc @Henni @DJaeger @brantje

**Comment by jancborchardt** [comment]
Well, it’s a maps marker icon. It’s a common place marker metaphor used in many maps apps. I suggest for @libasys to change the Pinit icon.
