### ISSUE TITLE
Error while running phpunit

### ISSUE THREAD

**Issue by nutzmdm** [owncloud/maps#80]
While running : 

phpunit tests/

I get : 
PHP Fatal error:  require_once(): Failed opening required '/var/www/owncloud/apps/maps/tests/../../../3rdparty/Pimple/Pimple.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/owncloud/apps/maps/tests/autoloader.php on line 12

**Comment by v1r0x** [comment]
anyone an idea?

cc @jancborchardt @Henni @DJaeger

**Comment by jancborchardt** [comment]
No idea, works on our Travis at least: https://travis-ci.org/owncloud/maps
