### ISSUE TITLE
Adding smth to favorites should show that marker as feedback

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#88]
When you don’t have the favorites layer enabled, it’s not apparent if the item was added to favorites. To fix this, maybe just enabling the favorites layer will do the trick. At the very least, show the marker for that favorite which was set just now as feedback.

cc @Henni @v1r0x :)

**Comment by DJaeger** [comment]
Maybe the user don't want the layer to be loaded, just to add a marker.

**Comment by jancborchardt** [comment]
True – but what we should do, as said above:

> show the marker for that favorite which was set just now as feedback.

**Comment by v1r0x** [comment]
Or we just display the yellow info popup on the top of the screen with a message?

**Comment by DJaeger** [comment]
Just a feedback sounds good.
And if the layer is active the user should also see the marker appearing.

**Comment by jancborchardt** [comment]
@v1r0x direct feedback in the form of how it will look like and where the action took place is much better. The notifications on top are intended more for general notifications, errors, and stuff which has no specific place.

**Comment by v1r0x** [comment]
What do you think about replacing the "Add to favorites" link in the popup with "Remove from favorites" or "Added"?

**Comment by Henni** [comment]
I agree with @jancborchardt.
We should show the newly created marker.
But we could remove it on the next click or fade it out after a few seconds.

**Comment by jancborchardt** [comment]
We should replace the link of course directly with »Remove from favorites« – it ideally should just be a star toggle next to the name of the place.

Then the marker should be shown, and it should not vanish. Otherwise you might think there was an error in saving it.

**Comment by DJaeger** [comment]
I have also thought about fade out, but that could also irritate the user like @jancborchardt said.
But it could also look irritating if there is only one marked shown.
And showing the whole layer could cause unwanted loading.

I thing the fade out would be the best.
Maybe fastly fade in, blinking 3 times to let the user realize it and slowly fade out?

**Comment by Henni** [comment]
@DJaeger such a animation might probably irritate users because there is too much happening (without real meaning).

I would propose that we implement it like @jancborchardt suggested. Show the newly created marker and don't animate (fade in, fade out, blink) it.

Afterwards we (and other users of the app) can test it and we can extend on it (in another PR).

**Comment by DJaeger** [comment]
Ok
