### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#9]
It should be possible to set points as favorites. They could be shown with star markers on the map, and this layer could be possible to disable in the sidebar.

Similarly, Contacts addresses could be shown as favorites by default (or at least the addresses of the contacts you set as favorite in the Contacts app).

cc @brantje

**Comment by acaparrelli** [comment]
I can't add favorites. When I click the ling on the POI nothing happens. Tks.

**Comment by jancborchardt** [comment]
cc @v1r0x for info. :)

**Comment by v1r0x** [comment]
I implemented it right now. But I don't know how to get/set the name of a favorite? WIth my JS "skills" I couldn't get the information of the added POI. Any ideas how to do this?

@jancborchardt 
cc @DJaeger @Henni

**Comment by jancborchardt** [comment]
cc @MorrisJobke @PVince81 @Henni for JS knowledge. :)

**Comment by acaparrelli** [comment]
Hi @v1r0x and @jancborchardt.
In these days I'm pretty busy, but as soon as I can I will take a look to that. Maybe joining our skills we can get through that :)

**Comment by jancborchardt** [comment]
@acaparrelli would be really cool to have you on board for the Maps app when you have more free time! :)

**Comment by acaparrelli** [comment]
I would love to do that @jancborchardt <https://github.com/jancborchardt>!

On 16/11/2015 11:27, Jan-Christoph Borchardt wrote:
>
> @acaparrelli <https://github.com/acaparrelli> would be really cool to
> have you on board for the Maps app when you have more free time! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/maps/issues/9#issuecomment-156982000>.
>

-- 
AC.

**Comment by v1r0x** [comment]
The most important question is what we want to store? Currently a user defined name, latitude, longitude, user_id and a timestamp is stored.

**Comment by jancborchardt** [comment]
Additionally what Maps.me seems to store is a group, color of marker (depends on group), and a Notes field.

**Comment by acaparrelli** [comment]
As Jan-Christoph I think a *Tag *(or we could call it /Group /or
/Category/) and a *Color *should be assigned to each POI.
This would be useful to group POIs (_restaurants_, _best stores_, _tapas
bars_, etc) and even to give the ability of embedding POIs Tag's maps in
public HTML websites. I mean, embed a map with _restaurants_ only or a
map with _restaurants_//+ _tapas bars_ + ...

Note field would be great too.


On 17/11/2015 12:50, v1r0x wrote:
>
> The most important question is what we want to store? Currently a user
> defined name, latitude, longitude, user_id and a timestamp is stored.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/maps/issues/9#issuecomment-157347504>.
>

-- 
AC.

**Comment by v1r0x** [comment]
So if I want to add @jancborchardt address as favorite, only the lat/lon is stored without the street, city, etc.?

**Comment by acaparrelli** [comment]
I think that storing city, street, number etc it would be more precise and future proof

**Comment by jancborchardt** [comment]
We need to use the lat/long because you can also add favorites in random places where there’s no address or when the thing you’re trying to favorite doesn’t exist yet on OpenStreetMap. An address can be supplementary, but can never be the identifying factor.

**Comment by v1r0x** [comment]
Should we only store lat/lon for now?

**Comment by jancborchardt** [comment]
Start small, yep. Lat/lon is the absolute minimum. Name is next – can be prefilled by the establishment you favorite, if it is any, and can be custom filled in the future. Everything else is additional.

**Comment by v1r0x** [comment]
Ok, I will create a PR with my code later

**Comment by v1r0x** [comment]
Create the PR #78 but the data in the DB is always NULL. Any idea what is wrong? @jancborchardt @Henni @DJaeger

**Comment by v1r0x** [comment]
Should we add the Favorite-Layer to the sidebar and showing them on the maps in the current PR #79 or in a new one?

**Comment by jancborchardt** [comment]
Separate one is better – always small steps. :)

**Comment by v1r0x** [comment]
Now that we have a very basic favorite functionality I'd like to collect the desired contents of this issue.
- [ ] Set favorite contacts as favorite marker by default
- [ ] Add a sidebar entry (toggle) for favorites
- [ ] display favorites
- [ ] Set user-defined name
- [ ] Remove marker?

Did I miss something?

**Comment by jancborchardt** [comment]
Yep, that's a good next step! I like the direct integration of favorite Contacts, good thinking.

**Comment by v1r0x** [comment]
It was your idea in the OP ;)

**Comment by jancborchardt** [comment]
@v1r0x lol :D I guess good job @jancborchardt then …

**Comment by Henni** [comment]
advanced todos:
- [ ] prettier icon (cc @jancborchardt )
- [ ] prevent duplicate favorites

*maybe these should be their own issues*

**Comment by v1r0x** [comment]
I think **all** icons should be prettier, not only the fav marker, so I would definitely move this to it's own issue

**Comment by v1r0x** [comment]
I tried to implement the contact favorite thing, but I couldn't find any API or entry in the VCARD which allows me to get the information if a contact is starred or not. Did I miss something or is it not possible?

**Comment by jancborchardt** [comment]
Is that possible with the new CardDAV API? @Henni @DeepDiver1975

**Comment by jancborchardt** [comment]
It’s all in the individual issues now so I’m closing this. Also see »Ability to remove favorites« https://github.com/owncloud/maps/issues/95
