### ISSUE TITLE
Get directions not working

### ISSUE THREAD

**Issue by zaphbbrox** [owncloud/maps#92]
Apparently the navigation isn't working. I can search for locations but the app doesn't show me any directions between the different points.
Is it already implemented?
Owncloud log doesn't show anything..

**Comment by v1r0x** [comment]
Doesn't work for me, too.
I'll look into it.

**Comment by v1r0x** [comment]
This should have been fixed in #111, please test it with current master if it works for you and reopen if your problem still persists.
