### ISSUE TITLE
Username shown in parentheses behind favorites label

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#93]
@v1r0x any specific reason why this happens? It’s really strange in a single-user environment, and even when you have multiple users but nothing shared.

**Comment by v1r0x** [comment]
I think this a debug relict ;)

**Comment by jancborchardt** [comment]
Let's get rid of it ;)

**Comment by v1r0x** [comment]
Come to the CCH then ;)

**Comment by jancborchardt** [comment]
Yep, still at BSides right across at the university. So either later or tomorrow. :)

**Comment by v1r0x** [comment]
Have fun there. I will be here til at least 2 am. So if you have some free time :D
